
import Navbar from '@/components/navbar'
import Sidebar from '@/components/sidebar'
import { checkSubscription } from '@/lib/subscription'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'RootLayout',
  description: 'Generated by create next app',
}

export default async function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const isPro = await checkSubscription();
  return (
        <div className='h-full'>
            <Navbar isPro={isPro}/>
            <div className='hidden md:flex mt-16 w-20 flex-col fixed inset-y-0'>
              <Sidebar isPro={isPro}/>
            </div>
            <main className='md:pl-20 pt-16 h-full'>
                {children}
            </main>
        </div>
  )
}
